In [2]:
import pandas as pd
import numpy as np

In [4]:
import os
from pathlib import Path

print("✅ Current working directory:")
print(os.getcwd())

print("\n✅ Files in current folder:")
print(os.listdir("."))

print("\n✅ Files in parent folder:")
print(os.listdir(".."))

print("\n✅ Checking if data folder exists:")
print("..\\data exists?", os.path.exists("../data"))

if os.path.exists("../data"):
    print("\n✅ Files inside ../data :")
    print(os.listdir("../data"))

✅ Current working directory:
c:\Users\PRIYAL\Downloads\Nostalgia_Trend_Project\Nostalgia_Trend_Project\Nostalgia_Trend_Project\notebooks

✅ Files in current folder:
['01_preprocessing.ipynb', '02_feature_engineering.ipynb']

✅ Files in parent folder:
['data', 'models', 'notebooks', 'powerbi', 'report']

✅ Checking if data folder exists:
..\data exists? True

✅ Files inside ../data :
['Cleaned_Viral_Social_Media_Trends.csv', 'final_ai_trend_analysis.csv', 'final_cluster_summary.csv', 'social_media_trends.csv', 'Viral_Social_Media_Trends.csv']

In [5]:
df = pd.read_csv("../data/cleaned_viral_Social_Media_Trends.csv")
df.head()

,Post_ID,Post_Date,Platform,Hashtag,Content_Type,Region,Views,Likes,Shares,Comments,Engagement_Level
0,Post_1,2022-01-13,TikTok,#Challenge,Video,UK,4163464,339431,53135,19346,High
1,Post_2,2022-05-13,Instagram,#Education,Shorts,India,4155940,215240,65860,27239,Medium
2,Post_3,2022-01-07,Twitter,#Challenge,Video,Brazil,3666211,327143,39423,36223,Medium
3,Post_4,2022-12-05,YouTube,#Education,Shorts,Australia,917951,127125,11687,36806,Low
4,Post_5,2023-03-23,TikTok,#Dance,Post,Brazil,64866,171361,69581,6376,Medium

In [6]:
df.columns = df.columns.str.strip().str.lower()
print(df.columns)

Index(['post_id', 'post_date', 'platform', 'hashtag', 'content_type', 'region',
       'views', 'likes', 'shares', 'comments', 'engagement_level'],
      dtype='str')

In [7]:
path = "../data/cleaned_viral_Social_Media_Trends.csv"

print("File exists?", os.path.exists(path))
df = pd.read_csv(path)

print("Loaded shape:", df.shape)
print("Columns:", list(df.columns))
df.head()

File exists? True
Loaded shape: (5000, 11)
Columns: ['Post_ID', 'Post_Date', 'Platform', 'Hashtag', 'Content_Type', 'Region', 'Views', 'Likes', 'Shares', 'Comments', 'Engagement_Level']

,Post_ID,Post_Date,Platform,Hashtag,Content_Type,Region,Views,Likes,Shares,Comments,Engagement_Level
0,Post_1,2022-01-13,TikTok,#Challenge,Video,UK,4163464,339431,53135,19346,High
1,Post_2,2022-05-13,Instagram,#Education,Shorts,India,4155940,215240,65860,27239,Medium
2,Post_3,2022-01-07,Twitter,#Challenge,Video,Brazil,3666211,327143,39423,36223,Medium
3,Post_4,2022-12-05,YouTube,#Education,Shorts,Australia,917951,127125,11687,36806,Low
4,Post_5,2023-03-23,TikTok,#Dance,Post,Brazil,64866,171361,69581,6376,Medium

In [8]:
path = "../data/cleaned_viral_Social_Media_Trends.csv"

print("File exists?", os.path.exists(path))
df = pd.read_csv(path)

print("Loaded shape:", df.shape)
print("Columns:", list(df.columns))
df.head()

File exists? True
Loaded shape: (5000, 11)
Columns: ['Post_ID', 'Post_Date', 'Platform', 'Hashtag', 'Content_Type', 'Region', 'Views', 'Likes', 'Shares', 'Comments', 'Engagement_Level']

,Post_ID,Post_Date,Platform,Hashtag,Content_Type,Region,Views,Likes,Shares,Comments,Engagement_Level
0,Post_1,2022-01-13,TikTok,#Challenge,Video,UK,4163464,339431,53135,19346,High
1,Post_2,2022-05-13,Instagram,#Education,Shorts,India,4155940,215240,65860,27239,Medium
2,Post_3,2022-01-07,Twitter,#Challenge,Video,Brazil,3666211,327143,39423,36223,Medium
3,Post_4,2022-12-05,YouTube,#Education,Shorts,Australia,917951,127125,11687,36806,Low
4,Post_5,2023-03-23,TikTok,#Dance,Post,Brazil,64866,171361,69581,6376,Medium

In [9]:
needed = ["hashtag", "year"]
for col in needed:
    print(col, "exists?", col in df.columns)
""

hashtag exists? False
year exists? False

''

In [10]:
print(df.columns.tolist())

['Post_ID', 'Post_Date', 'Platform', 'Hashtag', 'Content_Type', 'Region', 'Views', 'Likes', 'Shares', 'Comments', 'Engagement_Level']

In [11]:
import pandas as pd
import numpy as np

# Clean column names
df.columns = df.columns.str.strip().str.lower()

print("✅ Columns found:", df.columns.tolist())

# ---- AUTO FIND HASHTAG COLUMN ----
possible_hashtag_cols = [
    "hashtag", "hashtags", "tag", "tags", "trend", "trends", "keyword", "keywords", "topic"
]

hashtag_col = None
for c in possible_hashtag_cols:
    if c in df.columns:
        hashtag_col = c
        break

if hashtag_col is None:
    # try partial match (e.g., "hash_tag", "hashtag_name")
    for c in df.columns:
        if "hash" in c or "tag" in c or "trend" in c or "keyword" in c:
            hashtag_col = c
            break

if hashtag_col is None:
    raise ValueError("❌ Could not find a hashtag/trend column. Paste df.columns.tolist() here.")

df["hashtag"] = df[hashtag_col].astype(str).str.strip().str.lower()
print("✅ Using hashtag column:", hashtag_col)


# ---- AUTO CREATE YEAR (and month if possible) ----
# 1) If year column exists with any name
possible_year_cols = ["year", "post_year", "created_year", "publish_year"]
year_col = None

for c in possible_year_cols:
    if c in df.columns:
        year_col = c
        break

# 2) Else find date column and extract year/month
possible_date_cols = ["date", "post_date", "created_at", "timestamp", "time", "published_at"]

date_col = None
for c in possible_date_cols:
    if c in df.columns:
        date_col = c
        break

if year_col is not None:
    df["year"] = pd.to_numeric(df[year_col], errors="coerce")
    print("✅ Using year column:", year_col)

elif date_col is not None:
    df[date_col] = pd.to_datetime(df[date_col], errors="coerce")
    df["year"] = df[date_col].dt.year
    df["month"] = df[date_col].dt.month
    print("✅ Created year/month from date column:", date_col)

else:
    # If no year and no date, we create a dummy year to allow project to continue
    df["year"] = 2026
    df["month"] = 1
    print("⚠️ No year/date column found. Created dummy year=2026, month=1 (project will still run).")


print("\n✅ Final check:")
print("hashtag exists?", "hashtag" in df.columns)
print("year exists?", "year" in df.columns)
df[["hashtag", "year"] + (["month"] if "month" in df.columns else [])].head()

✅ Columns found: ['post_id', 'post_date', 'platform', 'hashtag', 'content_type', 'region', 'views', 'likes', 'shares', 'comments', 'engagement_level']
✅ Using hashtag column: hashtag
✅ Created year/month from date column: post_date

✅ Final check:
hashtag exists? True
year exists? True

      hashtag  year  month
0  #challenge  2022      1
1  #education  2022      5
2  #challenge  2022      1
3  #education  2022     12
4      #dance  2023      3

In [12]:
# Engagement score (use whatever exists)
possible = ["likes", "comments", "shares", "views"]
available = [c for c in possible if c in df.columns]
for c in available:
    df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0)

df["engagement_score"] = df[available].sum(axis=1)

# Hashtag frequency
hashtag_year = df.groupby(["hashtag","year"]).size().reset_index(name="trend_count")
hashtag_year.head()

      hashtag  year  trend_count
0  #challenge  2022          259
1  #challenge  2023          248
2     #comedy  2022          250
3     #comedy  2023          255
4      #dance  2022          231

In [13]:
possible = ["likes", "comments", "shares", "views"]
available = [c for c in possible if c in df.columns]

print("Engagement columns found:", available)

for c in available:
    df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0)

df["engagement_score"] = df[available].sum(axis=1)
df[available + ["engagement_score"]].head()

Engagement columns found: ['likes', 'comments', 'shares', 'views']

    likes  comments  shares    views  engagement_score
0  339431     19346   53135  4163464           4575376
1  215240     27239   65860  4155940           4464279
2  327143     36223   39423  3666211           4069000
3  127125     36806   11687   917951           1093569
4  171361      6376   69581    64866            312184

In [14]:
hashtag_year = df.groupby(["hashtag","year"]).size().reset_index(name="trend_count")
hashtag_year.head(10)

      hashtag  year  trend_count
0  #challenge  2022          259
1  #challenge  2023          248
2     #comedy  2022          250
3     #comedy  2023          255
4      #dance  2022          231
5      #dance  2023          265
6  #education  2022          278
7  #education  2023          247
8    #fashion  2022          252
9    #fashion  2023          235

In [15]:
sort_cols = ["hashtag", "year"]
if "month" in df.columns:
    sort_cols.append("month")

df = df.sort_values(sort_cols).reset_index(drop=True)

df["engagement_growth"] = df.groupby("hashtag")["engagement_score"].pct_change()
df[["hashtag","year"] + (["month"] if "month" in df.columns else []) + ["engagement_score","engagement_growth"]].head(15)

       hashtag  year  month  engagement_score  engagement_growth
0   #challenge  2022      1           4575376                NaN
1   #challenge  2022      1           4069000          -0.110674
2   #challenge  2022      1           4400107           0.081373
3   #challenge  2022      1           1326844          -0.698452
4   #challenge  2022      1            554890          -0.581797
5   #challenge  2022      1           4741299           7.544575
6   #challenge  2022      1            227100          -0.952102
7   #challenge  2022      1           3147459          12.859353
8   #challenge  2022      1           3454379           0.097514
9   #challenge  2022      1           1315769          -0.619101
10  #challenge  2022      1           4990326           2.792707
11  #challenge  2022      1           3237222          -0.351300
12  #challenge  2022      1           3044955          -0.059393
13  #challenge  2022      1           2210161          -0.274156
14  #challenge  2022      1           1177947          -0.467031

In [16]:
threshold = 1.5   # 150% growth
df["revival_label"] = df["engagement_growth"].apply(lambda x: 1 if pd.notnull(x) and x > threshold else 0)

df["revival_label"].value_counts()

revival_label
0    4154
1     846
Name: count, dtype: int64

In [17]:
out_path = "../data/final_dataset.csv"
df.to_csv(out_path, index=False)

print("Saved:", out_path)
print("File exists now?", os.path.exists(out_path))

Saved: ../data/final_dataset.csv
File exists now? True